class Events:
    ORDER_CREATED = "order_created"
    ORDER_STATUS_CHANGED = "order_status_changed"
    B2B_LEAD_CREATED = "b2b_lead_created"
    CUSTOMER_REGISTERED = "customer_registered"
    COMPLAINT_RECEIVED = "complaint_received"
    FEEDBACK_RECEIVED = "feedback_received"
    IG_DM_RECEIVED = "ig_dm_received"
    EXPENSE_RECORDED = "expense_recorded"
    INCOME_RECORDED = "income_recorded"
    LARGE_EXPENSE_ALERT = "large_expense_alert"
    APPLICATION_RECEIVED = "application_received"
    EMPLOYEE_ADDED = "employee_added"
    CAMPAIGN_LAUNCHED = "campaign_launched"
    PROMO_CREATED = "promo_created"
    TASK_CREATED = "task_created"
    TASK_COMPLETED = "task_completed"
    NEW_MESSAGE = "new_message"
    DELIVERY_STATUS_REPORT = "DELIVERY_STATUS_REPORT"
    MAGAZINE_PUBLISHED = "magazine_published"
    FRANCHISE_REPORT_GENERATED = "franchise_report_generated"

class BotBusActions:
    GENERATE_MAGAZINE_FACTS = "generate_magazine_facts"
    GET_TOP_PRODUCTS = "get_top_products"
    PICK_RESTAURANT = "pick_restaurant_of_week"
    SELL_MAGAZINE_ADS = "sell_magazine_ads"
    DRAFT_MAGAZINE = "draft_magazine"
    PUBLISH_MAGAZINE = "publish_magazine"
